//! this file was generated by zig translate-c
// and has since been heavily modified.
//
// vma is © 2017-2026 Advanced Micro Devices (MIT License)

const vma = @This();

pub const AllocatorCreateFlags = packed struct(c_uint) {
    externally_synchronized_bit: bool = false,
    khr_dedicated_allocation_bit: bool = false,
    khr_bind_memory2_bit: bool = false,
    ext_memory_budget_bit: bool = false,
    amd_device_coherent_memory_bit: bool = false,
    buffer_device_address_bit: bool = false,
    ext_memory_priority_bit: bool = false,
    khr_maintenance4_bit: bool = false,
    khr_maintenance5_bit: bool = false,
    khr_external_memory_win32_bit: bool = false,
    _unused: u22 = 0,
};

pub const MemoryUsage = enum(c_uint) {
    unknown = 0,
    gpu_only = 1,
    cpu_only = 2,
    cpu_to_gpu = 3,
    gpu_to_cpu = 4,
    cpu_copy = 5,
    gpu_lazily_allocated = 6,
    auto = 7,
    auto_prefer_device = 8,
    auto_prefer_host = 9,
};

pub const AllocationCreateFlags = packed struct(c_uint) {
    dedicated_memory_bit: bool = false, // bit 0
    never_allocate_bit: bool = false, // bit 1
    mapped_bit: bool = false, // bit 2
    _unused_0: u2 = 0, // bits 3-4
    user_data_copy_string_bit: bool = false, // bit 5
    upper_address_bit: bool = false, // bit 6
    dont_bind_bit: bool = false, // bit 7
    within_budget_bit: bool = false, // bit 8
    can_alias_bit: bool = false, // bit 9
    host_access_sequential_write_bit: bool = false, // bit 10
    host_access_random_bit: bool = false, // bit 11
    host_access_allow_transfer_instead_bit: bool = false, // bit 12
    _unused_1: u3 = 0, // bits 13-15
    strategy_min_memory_bit: bool = false, // bit 16
    strategy_min_time_bit: bool = false, // bit 17
    strategy_min_offset_bit: bool = false, // bit 18
    _unused_2: u13 = 0, // bits 19-31

    // Note: VMA_ALLOCATION_CREATE_STRATEGY_BEST_FIT_BIT is an alias of strategy_min_memory_bit
    // Note: VMA_ALLOCATION_CREATE_STRATEGY_FIRST_FIT_BIT is an alias of strategy_min_time_bit
};

pub const VirtualAllocationCreateFlags = packed struct(c_uint) {
    _unused_0: u6 = 0, // bits 0-5
    upper_address_bit: bool = false, // bit 6
    _unused_1: u9 = 0, // bits 7-15
    strategy_min_memory_bit: bool = false, // bit 16
    strategy_min_time_bit: bool = false, // bit 17
    strategy_min_offset_bit: bool = false, // bit 18
    _unused_2: u13 = 0, // bits 19-31
};

pub const PoolCreateFlags = packed struct(c_uint) {
    _unused_0: u1 = 0,
    ignore_buffer_image_granularity_bit: bool = false,
    linear_algorithm_bit: bool = false,
    _unused_1: u29 = 0,
};

pub const FragmentationFlags = packed struct(c_uint) {
    fast_bit: bool = false,
    balanced_bit: bool = false,
    full_bit: bool = false,
    extensive_bit: bool = false,
    _unused: u28 = 0,
};

pub const DefragmentationMoveOperation = enum(c_uint) {
    copy = 0,
    ignore = 1,
    destroy = 2,
};

pub const VirtualBlockCreateFlags = packed struct(c_uint) {
    linear_algorithm_bit: bool = false,
    _unused: u31 = 0,
};

pub const Allocator = opaque {};
pub const Pool = opaque {};
pub const Allocation = opaque {};
pub const DefragmentationContext = opaque {};
pub const VirtualAllocation = opaque {};
pub const VirtualBlock = opaque {};

pub const PfnAllocateDeviceMemoryFunction = ?*const fn (allocator: *Allocator, memoryType: u32, memory: vk.DeviceMemory, size: vk.DeviceSize, pUserData: ?*anyopaque) callconv(.c) void;
pub const PfnFreeDeviceMemoryFunction = ?*const fn (allocator: *Allocator, memoryType: u32, memory: vk.DeviceMemory, size: vk.DeviceSize, pUserData: ?*anyopaque) callconv(.c) void;
pub const PfnCheckDefragmentationBreakFunction = ?*const fn (pUserData: ?*anyopaque) callconv(.c) vk.Bool32;

pub const DeviceMemoryCallbacks = extern struct {
    pfnAllocate: PfnAllocateDeviceMemoryFunction = null,
    pfnFree: PfnFreeDeviceMemoryFunction = null,
    pUserData: ?*anyopaque = null,
};

pub const VulkanFunctions = extern struct {
    vkGetInstanceProcAddr: ?vk.PfnGetInstanceProcAddr = null,
    vkGetDeviceProcAddr: ?vk.PfnGetDeviceProcAddr = null,
    vkGetPhysicalDeviceProperties: ?vk.PfnGetPhysicalDeviceProperties = null,
    vkGetPhysicalDeviceMemoryProperties: ?vk.PfnGetPhysicalDeviceMemoryProperties = null,
    vkAllocateMemory: ?vk.PfnAllocateMemory = null,
    vkFreeMemory: ?vk.PfnFreeMemory = null,
    vkMapMemory: ?vk.PfnMapMemory = null,
    vkUnmapMemory: ?vk.PfnUnmapMemory = null,
    vkFlushMappedMemoryRanges: ?vk.PfnFlushMappedMemoryRanges = null,
    vkInvalidateMappedMemoryRanges: ?vk.PfnInvalidateMappedMemoryRanges = null,
    vkBindBufferMemory: ?vk.PfnBindBufferMemory = null,
    vkBindImageMemory: ?vk.PfnBindImageMemory = null,
    vkGetBufferMemoryRequirements: ?vk.PfnGetBufferMemoryRequirements = null,
    vkGetImageMemoryRequirements: ?vk.PfnGetImageMemoryRequirements = null,
    vkCreateBuffer: ?vk.PfnCreateBuffer = null,
    vkDestroyBuffer: ?vk.PfnDestroyBuffer = null,
    vkCreateImage: ?vk.PfnCreateImage = null,
    vkDestroyImage: ?vk.PfnDestroyImage = null,
    vkCmdCopyBuffer: ?vk.PfnCmdCopyBuffer = null,
    vkGetBufferMemoryRequirements2KHR: ?vk.PfnGetBufferMemoryRequirements2KHR = null,
    vkGetImageMemoryRequirements2KHR: ?vk.PfnGetImageMemoryRequirements2KHR = null,
    vkBindBufferMemory2KHR: ?vk.PfnBindBufferMemory2KHR = null,
    vkBindImageMemory2KHR: ?vk.PfnBindImageMemory2KHR = null,
    vkGetPhysicalDeviceMemoryProperties2KHR: ?vk.PfnGetPhysicalDeviceMemoryProperties2KHR = null,
    vkGetDeviceBufferMemoryRequirements: ?vk.PfnGetDeviceBufferMemoryRequirementsKHR = null,
    vkGetDeviceImageMemoryRequirements: ?vk.PfnGetDeviceImageMemoryRequirementsKHR = null,
    vkGetMemoryWin32HandleKHR: ?*anyopaque = null,
    vkGetPhysicalDeviceProperties2KHR: ?vk.PfnGetPhysicalDeviceProperties2KHR = null,
};

pub const AllocatorCreateInfo = extern struct {
    flags: AllocatorCreateFlags = .{},
    physicalDevice: vk.PhysicalDevice = .null_handle,
    device: vk.Device = .null_handle,
    preferredLargeHeapBlockSize: vk.DeviceSize = 0,
    pAllocationCallbacks: ?*const vk.AllocationCallbacks = null,
    pDeviceMemoryCallbacks: ?*const DeviceMemoryCallbacks = null,
    pHeapSizeLimit: ?*const vk.DeviceSize = null,
    pVulkanFunctions: ?*const VulkanFunctions = null,
    instance: vk.Instance = .null_handle,
    vulkanApiVersion: u32 = 0,
    pTypeExternalMemoryHandleTypes: ?*const vk.ExternalMemoryHandleTypeFlagsKHR = null,
};

pub const AllocatorInfo = extern struct {
    instance: vk.Instance = .null_handle,
    physicalDevice: vk.PhysicalDevice = .null_handle,
    device: vk.Device = .null_handle,
};

pub const Statistics = extern struct {
    blockCount: u32 = 0,
    allocationCount: u32 = 0,
    blockBytes: vk.DeviceSize = 0,
    allocationBytes: vk.DeviceSize = 0,
};

pub const DetailedStatistics = extern struct {
    statistics: Statistics = .{},
    unusedRangeCount: u32 = 0,
    allocationSizeMin: vk.DeviceSize = 0,
    allocationSizeMax: vk.DeviceSize = 0,
    unusedRangeSizeMin: vk.DeviceSize = 0,
    unusedRangeSizeMax: vk.DeviceSize = 0,
};

pub const TotalStatistics = extern struct {
    memoryType: [32]DetailedStatistics = @splat(.{}),
    memoryHeap: [16]DetailedStatistics = @splat(.{}),
    total: DetailedStatistics = .{},
};

pub const Budget = extern struct {
    statistics: Statistics = .{},
    usage: vk.DeviceSize = 0,
    budget: vk.DeviceSize = 0,
};

pub const AllocationCreateInfo = extern struct {
    flags: AllocationCreateFlags = .{},
    usage: MemoryUsage = .unknown,
    requiredFlags: vk.MemoryPropertyFlags = .{},
    preferredFlags: vk.MemoryPropertyFlags = .{},
    memoryTypeBits: u32 = 0,
    pool: ?*Pool = null,
    pUserData: ?*anyopaque = null,
    priority: f32 = 0,
    minAlignment: vk.DeviceSize = 0,
};

pub const PoolCreateInfo = extern struct {
    memoryTypeIndex: u32 = 0,
    flags: PoolCreateFlags = .{},
    blockSize: vk.DeviceSize = 0,
    minBlockCount: usize = 0,
    maxBlockCount: usize = 0,
    priority: f32 = 0,
    minAllocationAlignment: vk.DeviceSize = 0,
    pMemoryAllocateNext: ?*anyopaque = null,
};

pub const AllocationInfo = extern struct {
    memoryType: u32 = 0,
    deviceMemory: vk.DeviceMemory = .null_handle,
    offset: vk.DeviceSize = 0,
    size: vk.DeviceSize = 0,
    pMappedData: ?*anyopaque = null,
    pUserData: ?*anyopaque = null,
    pName: ?[*:0]const u8 = null,
};

pub const AllocationInfo2 = extern struct {
    allocationInfo: AllocationInfo = .{},
    blockSize: vk.DeviceSize = 0,
    dedicatedMemory: vk.Bool32 = .false,
};

pub const DefragmentationInfo = extern struct {
    flags: FragmentationFlags = .{},
    pool: ?*Pool = null,
    maxBytesPerPass: vk.DeviceSize = 0,
    maxAllocationsPerPass: u32 = 0,
    pfnBreakCallback: PfnCheckDefragmentationBreakFunction = null,
    pBreakCallbackUserData: ?*anyopaque = null,
};

pub const DefragmentationMove = extern struct {
    operation: DefragmentationMoveOperation = .{},
    srcAllocation: *Allocation = null,
    dstTmpAllocation: *Allocation = null,
};

pub const DefragmentationPassMoveInfo = extern struct {
    moveCount: u32 = 0,
    pMoves: ?[*]DefragmentationMove = null,
};

pub const DefragmentationStats = extern struct {
    bytesMoved: vk.DeviceSize = 0,
    bytesFreed: vk.DeviceSize = 0,
    allocationsMoved: u32 = 0,
    deviceMemoryBlocksFreed: u32 = 0,
};

pub const VirtualBlockCreateInfo = extern struct {
    size: vk.DeviceSize = 0,
    flags: VirtualBlockCreateFlags = .{},
    pAllocationCallbacks: ?[*]const vk.AllocationCallbacks = null,
};

pub const VirtualAllocationCreateInfo = extern struct {
    size: vk.DeviceSize = 0,
    alignment: vk.DeviceSize = 0,
    flags: VirtualAllocationCreateFlags = .{},
    pUserData: ?*anyopaque = null,
};

pub const VirtualAllocationInfo = extern struct {
    offset: vk.DeviceSize = 0,
    size: vk.DeviceSize = 0,
    pUserData: ?*anyopaque = null,
};

pub const Error = error{
    OutOfHostMemory,
    OutOfDeviceMemory,
    InitializationFailed,
    MemoryMapFailed,
    DeviceLost,
    InvalidOpaqueCaptureAddress,
    Unknown,
};

fn checkResult(result: vk.Result) Error!void {
    return switch (result) {
        .success => {},
        .error_out_of_host_memory => error.OutOfHostMemory,
        .error_out_of_device_memory => error.OutOfDeviceMemory,
        .error_initialization_failed => error.InitializationFailed,
        .error_memory_map_failed => error.MemoryMapFailed,
        .error_device_lost => error.DeviceLost,
        .error_invalid_opaque_capture_address => error.InvalidOpaqueCaptureAddress,
        else => error.Unknown,
    };
}

pub fn createAllocator(create_info: AllocatorCreateInfo) Error!*Allocator {
    var allocator: *Allocator = undefined;
    try checkResult(raw_api.vmaCreateAllocator(&create_info, &allocator));
    return allocator;
}

pub fn destroyAllocator(allocator: *Allocator) void {
    raw_api.vmaDestroyAllocator(allocator);
}

pub fn getAllocatorInfo(allocator: *Allocator) AllocatorInfo {
    var info: AllocatorInfo = undefined;
    raw_api.vmaGetAllocatorInfo(allocator, &info);
    return info;
}

pub fn calculateStatistics(allocator: *Allocator) TotalStatistics {
    var stats: TotalStatistics = undefined;
    raw_api.vmaCalculateStatistics(allocator, &stats);
    return stats;
}

pub fn getHeapBudgets(allocator: *Allocator) Budget {
    var budget: Budget = undefined;
    raw_api.vmaGetHeapBudgets(allocator, &budget);
    return budget;
}

pub fn findMemoryTypeIndex(
    allocator: *Allocator,
    memory_type_bits: u32,
    allocation_create_info: AllocationCreateInfo,
) Error!u32 {
    var index: u32 = undefined;
    try checkResult(raw_api.vmaFindMemoryTypeIndex(allocator, memory_type_bits, &allocation_create_info, &index));
    return index;
}

pub fn createPool(allocator: *Allocator, create_info: PoolCreateInfo) Error!*Pool {
    var pool: *Pool = undefined;
    try checkResult(raw_api.vmaCreatePool(allocator, &create_info, &pool));
    return pool;
}

pub fn destroyPool(allocator: *Allocator, pool: *Pool) void {
    raw_api.vmaDestroyPool(allocator, pool);
}

pub const BufferResult = struct {
    buffer: vk.Buffer,
    allocation: *Allocation,
    allocation_info: AllocationInfo,
};

pub fn createBuffer(
    allocator: *Allocator,
    buffer_create_info: vk.BufferCreateInfo,
    allocation_create_info: AllocationCreateInfo,
) Error!BufferResult {
    var result: BufferResult = undefined;
    try checkResult(raw_api.vmaCreateBuffer(
        allocator,
        &buffer_create_info,
        &allocation_create_info,
        &result.buffer,
        &result.allocation,
        &result.allocation_info,
    ));
    return result;
}

pub fn destroyBuffer(allocator: *Allocator, buffer: vk.Buffer, allocation: *Allocation) void {
    raw_api.vmaDestroyBuffer(allocator, buffer, allocation);
}

pub const ImageResult = struct {
    image: vk.Image,
    allocation: *Allocation,
    allocation_info: AllocationInfo,
};

pub fn createImage(
    allocator: *Allocator,
    image_create_info: vk.ImageCreateInfo,
    allocation_create_info: AllocationCreateInfo,
) Error!ImageResult {
    var result: ImageResult = undefined;
    try checkResult(raw_api.vmaCreateImage(
        allocator,
        &image_create_info,
        &allocation_create_info,
        &result.image,
        &result.allocation,
        &result.allocation_info,
    ));
    return result;
}

pub fn destroyImage(allocator: *Allocator, image: vk.Image, allocation: *Allocation) void {
    raw_api.vmaDestroyImage(allocator, image, allocation);
}

pub const AllocationResult = struct {
    allocation: *Allocation,
    allocation_info: AllocationInfo,
};

pub fn allocateMemory(
    allocator: *Allocator,
    memory_requirements: vk.MemoryRequirements,
    allocation_create_info: AllocationCreateInfo,
) Error!AllocationResult {
    var result: AllocationResult = undefined;
    try checkResult(raw_api.vmaAllocateMemory(
        allocator,
        &memory_requirements,
        &allocation_create_info,
        &result.allocation,
        &result.allocation_info,
    ));
    return result;
}

pub fn freeMemory(allocator: *Allocator, allocation: *Allocation) void {
    raw_api.vmaFreeMemory(allocator, allocation);
}

pub fn mapMemory(allocator: *Allocator, allocation: *Allocation) Error!*anyopaque {
    var ptr: ?*anyopaque = null;
    try checkResult(raw_api.vmaMapMemory(allocator, allocation, &ptr));
    return ptr orelse return error.Unknown;
}

pub fn unmapMemory(allocator: *Allocator, allocation: *Allocation) void {
    raw_api.vmaUnmapMemory(allocator, allocation);
}

pub fn getAllocationInfo(allocator: *Allocator, allocation: *Allocation) AllocationInfo {
    var info: AllocationInfo = undefined;
    raw_api.vmaGetAllocationInfo(allocator, allocation, &info);
    return info;
}

const raw_api = struct {
    pub extern fn vmaCreateAllocator(pCreateInfo: *const AllocatorCreateInfo, pAllocator: **Allocator) vk.Result;
    pub extern fn vmaDestroyAllocator(allocator: *Allocator) void;
    pub extern fn vmaGetAllocatorInfo(allocator: *Allocator, pAllocatorInfo: *AllocatorInfo) void;
    pub extern fn vmaGetPhysicalDeviceProperties(allocator: *Allocator, ppPhysicalDeviceProperties: **const vk.PhysicalDeviceProperties) void;
    pub extern fn vmaGetMemoryProperties(allocator: *Allocator, ppPhysicalDeviceMemoryProperties: **const vk.PhysicalDeviceMemoryProperties) void;
    pub extern fn vmaGetMemoryTypeProperties(allocator: *Allocator, memoryTypeIndex: u32, pFlags: *vk.MemoryPropertyFlags) void;
    pub extern fn vmaSetCurrentFrameIndex(allocator: *Allocator, frameIndex: u32) void;
    pub extern fn vmaCalculateStatistics(allocator: *Allocator, pStats: *TotalStatistics) void;
    pub extern fn vmaGetHeapBudgets(allocator: *Allocator, pBudgets: *Budget) void;
    pub extern fn vmaFindMemoryTypeIndex(allocator: *Allocator, memoryTypeBits: u32, pAllocationCreateInfo: *const AllocationCreateInfo, pMemoryTypeIndex: *u32) vk.Result;
    pub extern fn vmaFindMemoryTypeIndexForBufferInfo(allocator: *Allocator, pBufferCreateInfo: *const vk.BufferCreateInfo, pAllocationCreateInfo: *const AllocationCreateInfo, pMemoryTypeIndex: *u32) vk.Result;
    pub extern fn vmaFindMemoryTypeIndexForImageInfo(allocator: *Allocator, pImageCreateInfo: *const vk.ImageCreateInfo, pAllocationCreateInfo: *const AllocationCreateInfo, pMemoryTypeIndex: *u32) vk.Result;
    pub extern fn vmaCreatePool(allocator: *Allocator, pCreateInfo: *const PoolCreateInfo, pPool: **Pool) vk.Result;
    pub extern fn vmaDestroyPool(allocator: *Allocator, pool: *Pool) void;
    pub extern fn vmaGetPoolStatistics(allocator: *Allocator, pool: *Pool, pPoolStats: *Statistics) void;
    pub extern fn vmaCalculatePoolStatistics(allocator: *Allocator, pool: *Pool, pPoolStats: *DetailedStatistics) void;
    pub extern fn vmaCheckPoolCorruption(allocator: *Allocator, pool: *Pool) vk.Result;
    pub extern fn vmaGetPoolName(allocator: *Allocator, pool: *Pool, ppName: *[*:0]const u8) void;
    pub extern fn vmaSetPoolName(allocator: *Allocator, pool: *Pool, pName: [*:0]const u8) void;
    pub extern fn vmaAllocateMemory(allocator: *Allocator, pVkMemoryRequirements: *const vk.MemoryRequirements, pCreateInfo: *const AllocationCreateInfo, pAllocation: **Allocation, pAllocationInfo: *AllocationInfo) vk.Result;
    pub extern fn vmaAllocateDedicatedMemory(allocator: *Allocator, pVkMemoryRequirements: *const vk.MemoryRequirements, pCreateInfo: *const AllocationCreateInfo, pMemoryAllocateNext: ?*anyopaque, pAllocation: **Allocation, pAllocationInfo: *AllocationInfo) vk.Result;
    pub extern fn vmaAllocateMemoryPages(allocator: *Allocator, pVkMemoryRequirements: *const vk.MemoryRequirements, pCreateInfo: *const AllocationCreateInfo, allocationCount: usize, pAllocations: **Allocation, pAllocationInfo: *AllocationInfo) vk.Result;
    pub extern fn vmaAllocateMemoryForBuffer(allocator: *Allocator, buffer: vk.Buffer, pCreateInfo: *const AllocationCreateInfo, pAllocation: **Allocation, pAllocationInfo: *AllocationInfo) vk.Result;
    pub extern fn vmaAllocateMemoryForImage(allocator: *Allocator, image: vk.Image, pCreateInfo: *const AllocationCreateInfo, pAllocation: **Allocation, pAllocationInfo: *AllocationInfo) vk.Result;
    pub extern fn vmaFreeMemory(allocator: *Allocator, allocation: *Allocation) void;
    pub extern fn vmaFreeMemoryPages(allocator: *Allocator, allocationCount: usize, pAllocations: [*]const *Allocation) void;
    pub extern fn vmaGetAllocationInfo(allocator: *Allocator, allocation: *Allocation, pAllocationInfo: *AllocationInfo) void;
    pub extern fn vmaGetAllocationInfo2(allocator: *Allocator, allocation: *Allocation, pAllocationInfo: *AllocationInfo2) void;
    pub extern fn vmaSetAllocationUserData(allocator: *Allocator, allocation: *Allocation, pUserData: ?*anyopaque) void;
    pub extern fn vmaSetAllocationName(allocator: *Allocator, allocation: *Allocation, pName: [*:0]const u8) void;
    pub extern fn vmaGetAllocationMemoryProperties(allocator: *Allocator, allocation: *Allocation, pFlags: *vk.MemoryPropertyFlags) void;
    pub extern fn vmaMapMemory(allocator: *Allocator, allocation: *Allocation, ppData: *?*anyopaque) vk.Result;
    pub extern fn vmaUnmapMemory(allocator: *Allocator, allocation: *Allocation) void;
    pub extern fn vmaFlushAllocation(allocator: *Allocator, allocation: *Allocation, offset: vk.DeviceSize, size: vk.DeviceSize) vk.Result;
    pub extern fn vmaInvalidateAllocation(allocator: *Allocator, allocation: *Allocation, offset: vk.DeviceSize, size: vk.DeviceSize) vk.Result;
    pub extern fn vmaFlushAllocations(allocator: *Allocator, allocationCount: u32, allocations: [*]const *Allocation, offsets: [*]const vk.DeviceSize, sizes: [*]const vk.DeviceSize) vk.Result;
    pub extern fn vmaInvalidateAllocations(allocator: *Allocator, allocationCount: u32, allocations: [*]const *Allocation, offsets: [*]const vk.DeviceSize, sizes: [*]const vk.DeviceSize) vk.Result;
    pub extern fn vmaCopyMemoryToAllocation(allocator: *Allocator, pSrcHostPointer: ?*const anyopaque, dstAllocation: *Allocation, dstAllocationLocalOffset: vk.DeviceSize, size: vk.DeviceSize) vk.Result;
    pub extern fn vmaCopyAllocationToMemory(allocator: *Allocator, srcAllocation: *Allocation, srcAllocationLocalOffset: vk.DeviceSize, pDstHostPointer: ?*anyopaque, size: vk.DeviceSize) vk.Result;
    pub extern fn vmaCheckCorruption(allocator: *Allocator, memoryTypeBits: u32) vk.Result;
    pub extern fn vmaBeginDefragmentation(allocator: *Allocator, pInfo: *const DefragmentationInfo, pContext: **DefragmentationContext) vk.Result;
    pub extern fn vmaEndDefragmentation(allocator: *Allocator, context: *DefragmentationContext, pStats: *DefragmentationStats) void;
    pub extern fn vmaBeginDefragmentationPass(allocator: *Allocator, context: *DefragmentationContext, pPassInfo: *DefragmentationPassMoveInfo) vk.Result;
    pub extern fn vmaEndDefragmentationPass(allocator: *Allocator, context: *DefragmentationContext, pPassInfo: *DefragmentationPassMoveInfo) vk.Result;
    pub extern fn vmaBindBufferMemory(allocator: *Allocator, allocation: *Allocation, buffer: vk.Buffer) vk.Result;
    pub extern fn vmaBindBufferMemory2(allocator: *Allocator, allocation: *Allocation, allocationLocalOffset: vk.DeviceSize, buffer: vk.Buffer, pNext: ?*const anyopaque) vk.Result;
    pub extern fn vmaBindImageMemory(allocator: *Allocator, allocation: *Allocation, image: vk.Image) vk.Result;
    pub extern fn vmaBindImageMemory2(allocator: *Allocator, allocation: *Allocation, allocationLocalOffset: vk.DeviceSize, image: vk.Image, pNext: ?*const anyopaque) vk.Result;
    pub extern fn vmaCreateBuffer(allocator: *Allocator, pBufferCreateInfo: *const vk.BufferCreateInfo, pAllocationCreateInfo: *const AllocationCreateInfo, pBuffer: *vk.Buffer, pAllocation: **Allocation, pAllocationInfo: *AllocationInfo) vk.Result;
    pub extern fn vmaCreateBufferWithAlignment(allocator: *Allocator, pBufferCreateInfo: *const vk.BufferCreateInfo, pAllocationCreateInfo: *const AllocationCreateInfo, minAlignment: vk.DeviceSize, pBuffer: *vk.Buffer, pAllocation: **Allocation, pAllocationInfo: *AllocationInfo) vk.Result;
    pub extern fn vmaCreateDedicatedBuffer(allocator: *Allocator, pBufferCreateInfo: *const vk.BufferCreateInfo, pAllocationCreateInfo: *const AllocationCreateInfo, pMemoryAllocateNext: ?*anyopaque, pBuffer: *vk.Buffer, pAllocation: **Allocation, pAllocationInfo: *AllocationInfo) vk.Result;
    pub extern fn vmaCreateAliasingBuffer(allocator: *Allocator, allocation: *Allocation, pBufferCreateInfo: *const vk.BufferCreateInfo, pBuffer: *vk.Buffer) vk.Result;
    pub extern fn vmaCreateAliasingBuffer2(allocator: *Allocator, allocation: *Allocation, allocationLocalOffset: vk.DeviceSize, pBufferCreateInfo: *const vk.BufferCreateInfo, pBuffer: *vk.Buffer) vk.Result;
    pub extern fn vmaDestroyBuffer(allocator: *Allocator, buffer: vk.Buffer, allocation: *Allocation) void;
    pub extern fn vmaCreateImage(allocator: *Allocator, pImageCreateInfo: *const vk.ImageCreateInfo, pAllocationCreateInfo: *const AllocationCreateInfo, pImage: *vk.Image, pAllocation: **Allocation, pAllocationInfo: *AllocationInfo) vk.Result;
    pub extern fn vmaCreateDedicatedImage(allocator: *Allocator, pImageCreateInfo: *const vk.ImageCreateInfo, pAllocationCreateInfo: *const AllocationCreateInfo, pMemoryAllocateNext: ?*anyopaque, pImage: *vk.Image, pAllocation: **Allocation, pAllocationInfo: *AllocationInfo) vk.Result;
    pub extern fn vmaCreateAliasingImage(allocator: *Allocator, allocation: *Allocation, pImageCreateInfo: *const vk.ImageCreateInfo, pImage: *vk.Image) vk.Result;
    pub extern fn vmaCreateAliasingImage2(allocator: *Allocator, allocation: *Allocation, allocationLocalOffset: vk.DeviceSize, pImageCreateInfo: *const vk.ImageCreateInfo, pImage: *vk.Image) vk.Result;
    pub extern fn vmaDestroyImage(allocator: *Allocator, image: vk.Image, allocation: *Allocation) void;
    pub extern fn vmaCreateVirtualBlock(pCreateInfo: *const VirtualBlockCreateInfo, pVirtualBlock: **VirtualBlock) vk.Result;
    pub extern fn vmaDestroyVirtualBlock(virtualBlock: *VirtualBlock) void;
    pub extern fn vmaIsVirtualBlockEmpty(virtualBlock: *VirtualBlock) vk.Bool32;
    pub extern fn vmaGetVirtualAllocationInfo(virtualBlock: *VirtualBlock, allocation: *VirtualAllocation, pVirtualAllocInfo: *VirtualAllocationInfo) void;
    pub extern fn vmaVirtualAllocate(virtualBlock: *VirtualBlock, pCreateInfo: *const VirtualAllocationCreateInfo, pAllocation: **VirtualAllocation, pOffset: *vk.DeviceSize) vk.Result;
    pub extern fn vmaVirtualFree(virtualBlock: *VirtualBlock, allocation: *VirtualAllocation) void;
    pub extern fn vmaClearVirtualBlock(virtualBlock: *VirtualBlock) void;
    pub extern fn vmaSetVirtualAllocationUserData(virtualBlock: *VirtualBlock, allocation: *VirtualAllocation, pUserData: ?*anyopaque) void;
    pub extern fn vmaGetVirtualBlockStatistics(virtualBlock: *VirtualBlock, pStats: *Statistics) void;
    pub extern fn vmaCalculateVirtualBlockStatistics(virtualBlock: *VirtualBlock, pStats: *DetailedStatistics) void;
    pub extern fn vmaBuildVirtualBlockStatsString(virtualBlock: *VirtualBlock, ppStatsString: *[*:0]u8, detailedMap: vk.Bool32) void;
    pub extern fn vmaFreeVirtualBlockStatsString(virtualBlock: *VirtualBlock, pStatsString: [*:0]u8) void;
    pub extern fn vmaBuildStatsString(allocator: *Allocator, ppStatsString: *[*:0]const u8, detailedMap: vk.Bool32) void;
    pub extern fn vmaFreeStatsString(allocator: *Allocator, pStatsString: [*:0]const u8) void;
};

const vk = @import("vulkan.zig");
const std = @import("std");
const log = std.log.scoped(.vma);
